<?php

    namespace weblogic\migrations;

    use yii\db\Migration;

    /**
     * Updates tasks table
     * @author rossmann-it
     */
    class m200919_195600_alter_for_timestamp_behaviour extends Migration
    {

        /**
         * for Oracle you need to overwrite the typeMap in \yii\db\oci\QueryBuilder
         * to get an equivalent for AUTO_INCREMENT, for example
         * 'NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY'
         */
        public function safeUp()
        {
            $this->addColumn('{{%task}}', 'created_at', $this->integer()->notNull()->defaultValue('UNIX_TIMESTAMP()'));
            $this->addColumn('{{%task}}', 'updated_at', $this->integer()->notNull()->defaultValue('UNIX_TIMESTAMP()'));
            $this->addColumn('{{%task_runs}}', 'created_at', $this->integer()->notNull()->defaultValue('UNIX_TIMESTAMP()'));

            $this->execute("
UPDATE `task` 
SET 
    `created_at` = UNIX_TIMESTAMP(`ts`), 
    `updated_at` = UNIX_TIMESTAMP(`ts_updated`)"
            );

            $this->execute("
UPDATE `task_runs` 
SET 
    `created_at` = UNIX_TIMESTAMP(`ts`)"
            );

            $this->dropColumn('{{%task}}', 'ts');
            $this->dropColumn('{{%task}}', 'ts_updated');
            $this->dropColumn('{{%task_runs}}', 'ts');
        }

        public function safeDown()
        {
            $this->addColumn('{{%task}}', 'created_at', $this->timestamp()->defaultExpression('CURRENT_TIMESTAMP'));
            $this->addColumn('{{%task}}', 'updated_at', $this->timestamp());
            $this->addColumn('{{%task_runs}}', 'created_at', $this->timestamp()->defaultExpression('CURRENT_TIMESTAMP'));


            $this->execute("
UPDATE `task` 
SET 
    `ts` = dateadd(`created_at`, [unixtime], '1970-01-01'), 
    `ts_updated` = dateadd(`updated_at`, [unixtime], '1970-01-01')"
            );

            $this->execute("
UPDATE `task_runs` 
SET 
    `ts` = dateadd(`created_at`, [unixtime], '1970-01-01')"
            );

            $this->dropColumn('{{%task}}', 'created_at');
            $this->dropColumn('{{%task}}', 'updated_at');
            $this->dropColumn('{{%task_runs}}', 'created_at');
        }
    }
